export const BASE_API = process.env.NEXT_PUBLIC_BASE_API

export const MODAL_TYPE = {
  DEFAULT: 'DEFAULT',
  SHARE: 'SHARE',
  RE_CART: 'RE_CART',
  DELETE: 'DELETE',
}

export const TEST_ACCESS_TOKEN =
  'eyJhbGciOiJIUzUxMiJ9.eyJzY29wZSI6Ik1BU1RFUiIsImp0aSI6ImU4ZmZkZTE5LWY1YTgtNGU3OC05NDMwLWM5NGJiZWQ5NzljMSIsInN1YiI6IjEiLCJpc3MiOiJjYXJ0IiwiaWF0IjoxNzMwNzk2NDA1LCJleHAiOjE3MzExNTY0MDV9.IAsIIYZv_JwoIAY6CtYiMwM_0z42TnzqL7uz5dmoSMowRMV7zNhonK1CqJJ7yZfYJ7GbJOJSbDR-GL9z7tq2Vg'
